# Generated by Django 6.0.1 on 2026-01-20 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_interes', models.DecimalField(decimal_places=2, help_text='Tasa mensual en %', max_digits=5)),
                ('plazo_meses', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('ACTIVO', 'Activo'), ('PAGADO', 'Pagado'), ('MORA', 'En Mora'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='creditos.cliente')),
            ],
        ),
    ]
